### ISSUE TITLE
Small typo in usage instructions

### ISSUE THREAD

**Issue by radu-corbu** [boydaihungst/simple-mtpfs.yazi#4]
Hello!

First of all, thanks very much for developing this plugin :) It helps take me one step closer to using Yazi as my main file manager, without relying on a fallback for operations like mounting my Android phone.

I want to report a minor issue. In the usage instructions, you mention this keybinding:

```toml
[manager]
prepend_keymap = [
# ...
    { on = [ "M", "m" ], run = "plugin simple-mtpfs -- 'select-then-mount --jump'", desc = "Select device to mount and jump to its mount point" },
# ...
```

But the command isn't correct. I've tried running it and nothing happens. The correct command is:

```toml
[manager]
prepend_keymap = [
# ...
    { on = [ "M", "m" ], run = "plugin simple-mtpfs -- select-then-mount --jump", desc = "Select device to mount and jump to its mount point" },
# ...
```
(need to remove the apostrophe `'` symbols).
